name: Build and publish test environment

on:
  workflow_dispatch: { }
  repository_dispatch:
    types: [ blockbind ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: blockbind/docker-testenv
          token: ${{ secrets.GH_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build project
        run: |
          git submodule update --init --recursive
          echo $PWD
          cd blockbind
          echo $PWD
          ls
          mvn package
      - name: Prepare artifact
        run: |
          mkdir artifact
          cp target/*.jar artifact/
          cp -r include/* artifact/
          zip -r testenv.zip artifact/*
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact/
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "${GITHUB_SHA}"
          files: |
            testenv.zip
            docker-compose.yml