name: Update test environment

on:
  workflow_dispatch: { }
  schedule:
    - cron: "*/59 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: blockbind/docker-testenv
          token: ${{ secrets.GH_TOKEN }}
          submodules: true
      - name: Pull & update submodules recursively
        run: |
          git submodule update --remote --merge
      - name: Commit & push changes
        run: |
          git commit -am "Update submodules"
          git push